version: "3"

services:
  ip_monit:
    build: .
    entrypoint: "/ip-monit/bin/docker-entrypoint.sh"
    ports:
      - 9494:9494
    networks:
      - share-network
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=servers_com
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - share-network
    ports:
      - 5432:5432
networks:
  share-network:
    driver: bridge
volumes:
  database_data:
    driver: local
